apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenoid
    spec:
      containers:
      - name: selenoid
        image: aerokube/selenoid:latest
        args: ["-limit", "10"]
        ports:
        - containerPort: 4444
        volumeMounts:
        - name: quota
          mountPath: /etc/selenoid
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
      - name: selenoid-ui
        image: aerokube/selenoid-ui:1.10.0
        args: ["-webdriver-uri", "http://localhost:4444"]
        ports:
        - name: selenoid-ui
          containerPort: 8080
      volumes:
      - name: quota
        configMap:
          name: quota
      - name: docker-sock-volume
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
  selector:
    matchLabels:
      app: selenoid

