---
apiVersion: v1
kind: Service
metadata:
  name: selenoid-svc
  namespace: default

spec:
  type: LoadBalancer
  ports:
  - name: selenoid
    protocol: TCP
    port: 4444
  - name: selenoid-ui
    protocol: TCP
    port: 8080
  selector:
    app: selenoid
