
name: My 
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-20.04
    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 1024
      #     swap-size-mb: 1024
      #     remove-dotnet: 'true'
      #     build-mount-path: '/'
      #       description: 'Absolute path to the mount point where the build space will be available, defaults to $GITHUB_WORKSPACE if unset.'
      #       required: false
      
      # - name: Cleanup disk
      #   uses: curoky/cleanup-disk-action@v2.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"  
          df -h
      - name: DockerImages
        run: |
          docker images
          docker ps -a
