
name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-20.04
    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 1024
      #     swap-size-mb: 1024
      #     remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Free space:"  
          df -h
      - name: DockerImages
        run: |
          docker images
          docker ps -a

      - name: Remove-Docker-images
        run: |
          docker rmi -f 9ff95a467e45 81bcf752ac3d acf04b8ccc37 e389ae589224 13621d1b12d4 
          docker images
          docker ps -a