name: 'ci-with-woke-spell'
on:
  - push
jobs:

  matrix:
    
    name: Run matrix
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node: [11, 12]
        os: [macos-latest, ubuntu-18.04]
        experimental: [false]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: truex
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.10.0