name: 'ci-with-spellcheck'
on:
  - push
jobs:

  matrix:
    
    name: Run matrix
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        node: [11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        os: [macos-latest, ubuntu-18.04]
        experimental: [true]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sleep
        run: |
          sleep 5